# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc09fd6ab6e2a46a382c726a7ee912bb4229e997acb6ec5140e3fc251ac66f5efbcc30f4c930be8d62453443e1f063c460915d5b8f004bb33c76e15f8d203ac

test:
  secret_key_base: e4b801623ec5845c02543f31e762be517f5b3b92af2afd2f1390cf208c99871e8e81990dbfde526798abe270c0c2212a10f198eef8f744a8992ff71c415a949f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
